# Generated by Django 5.2 on 2025-04-23 20:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='team_members', to='certs.team'),
        ),
        migrations.AlterField(
            model_name='privatekey',
            name='access_teams',
            field=models.ManyToManyField(related_name='private_key', to='certs.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='user_teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
