# Generated by Django 5.2 on 2025-04-23 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certs', '0002_alter_customuser_teams_alter_privatekey_access_teams_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='teams',
        ),
    ]
