# Generated by Django 5.2 on 2025-04-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certs', '0004_remove_certificate_cert_file_alter_team_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='content_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
