# Generated by Django 5.2 on 2025-04-24 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certs', '0005_uploadedfile_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
