# Generated by Django 5.2 on 2025-04-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certs', '0006_certificate_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatekey',
            name='keysize',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
