# Generated by Django 5.2 on 2025-04-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certs', '0007_privatekey_keysize'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatekey',
            name='key_hash',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
