# Generated by Django 5.2 on 2025-05-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certs', '0008_privatekey_key_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='access_teams',
            field=models.ManyToManyField(blank=True, related_name='certificates', to='certs.team'),
        ),
        migrations.AlterField(
            model_name='privatekey',
            name='access_teams',
            field=models.ManyToManyField(blank=True, related_name='private_key', to='certs.team'),
        ),
    ]
