# Generated by Django 5.2 on 2025-05-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certs', '0009_alter_certificate_access_teams_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privatekey',
            name='comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
