# Generated by Django 5.2 on 2025-05-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certs', '0012_alter_customuser_managers_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatekey',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
