# Generated by Django 5.2 on 2025-05-20 20:30

import certs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certs', '0014_invitetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitetoken',
            name='expires_at',
            field=models.DateTimeField(default=certs.models.default_invite_expiry),
        ),
    ]
